name: file_content
description: A new Flutter plugin to receive and share content.
version: 0.0.5
author: Bongga
homepage: https://bongga.co

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: co.bongga.file_content
    pluginClass: FileContentPlugin

